version: '2'
services:
  app:
    build: .
    environment:
      SHELL: '/bin/sh'
    labels:
      SERVICE_3000_NAME: sox-demo
      SERVICE_3000_TAGS: urlprefix-sox-demo.*/
      SERVICE_3000_CHECK_TCP: 'true'
      SERVICE_3000_CHECK_INTERVAL: 15s
    mem_reservation: "256m"
    ports:
      - 3000
    volumes:
      - 'db:/service/db'
      - '..:/service/node_modules/@articulate/sox'
      - './client:/service/client'
      - './package.json:/service/package.json'
      - './server:/service/server'
volumes:
  db:
